name: Github Actions 실행시켜보기

on:
    push:
        branches:
            - main

jobs:
    My-Deploy-job:
        runs-on: ubuntu-latest

        steps:
            - name: Hello World 출력하기
              run: echo "Hello World"


            - name: Github actions Secret 변수(적용 후)
              run: |
                echo ${{ secrets.MY_NAME }}
                echo ${{ secrets.MY_HOBBY }}